site_name: UAV Thesis
site_url: https://bwally0.github.io/uav-thesis/
nav:
  - Home: index.md
  - Architecture:
    - Overview: architecture/overview.md
    - Supervisor: architecture/supervisor.md
    - Decision Layer: architecture/decision.md
    - Control Layer: architecture/control.md
    - System Lifecycles: architecture/lifecycle.md
  - Tutorials:
    - Installation: tutorials/installation.md
    - Configuration: tutorials/configuration.md
theme: mkdocs